### ISSUE TITLE
Why define OrderedBatchRandomSampler?

### ISSUE THREAD

**Issue by WenxiongLiao** [XintianHan/Survival-MDN#3]
What is the purpose of defining OrderedBatchRandomSampler?

**Comment by XintianHan** [comment]
This is copied from SODEN not specifically used for Survival-MDN. You can probably post an issue there. My guess is that training SODEN probably requires the data ordered in time. But it's been a long time. I kind of forget.

**Comment by WenxiongLiao** [comment]
> This is copied from SODEN not specifically used for Survival-MDN. You can probably post an issue there. My guess is that training SODEN probably requires the data ordered in time. But it's been a long time. I kind of forget.

**What I mean is that Survival-MDN should be able to do without this OrderedBatchRandomSampler, right?**

**Comment by XintianHan** [comment]
> > This is copied from SODEN not specifically used for Survival-MDN. You can probably post an issue there. My guess is that training SODEN probably requires the data ordered in time. But it's been a long time. I kind of forget.
> 
> **What I mean is that Survival-MDN should be able to do without this OrderedBatchRandomSampler, right?**

I think so
